### PR TITLE
Run GitHub Actions on PRs

### PR DESCRIPTION
**Pull request by tagliala**
Hi, I've noticed that PRs do not run actions, so they can introduce issues that will only discovered when merged to master

Also:

- Set explicit permissions to read for better security. Workflows run
  with extended set of permissions by default. By specifying
  any permission explicitly, all others are set to none.
- Update actions to prevent deprecation warning messages
- Remove redundant `gem install bundler` (bundler is already available after
  setup-ruby action)
- Move Shakapacker checks to the main integration workflow

Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

---

Blocked by

- [x] jamesmartin/inline_svg_test_app#23
- [x] jamesmartin/inline_svg_test_app#24
- [x] #156

### CODE REVIEW

**Comment by tagliala** [comment]
I'm facing some issues related to the usage of an old version of webpacker which still uses node-sass, and Python 2.7 is not available anymore. I guess that https://github.com/jamesmartin/inline_svg_test_app/tree/rails6-webpacker needs an updated, but then we should use webpacker 5.x

**Comment by jamesmartin** [comment]
Thanks for opening this PR. New branch created in the `inline_svg_test_app` repo for `rails7-shakapacker` so you can get the integration tests running.

**Comment by tagliala** [comment]
Friendly bump.

The first step would be to merge

- jamesmartin/inline_svg_test_app#24
- jamesmartin/inline_svg_test_app#25
- jamesmartin/inline_svg_test_app#26

Then this one can be merged because it is not breaking.

Then it is possible to proceed, after a change to the target repo in actions, with:
- jamesmartin/inline_svg#159

At that point it would be possible to release a minor release.

After the minor release, it would be possible to consider to drop old Ruby and Rails support and go for 2.0

**Comment by tagliala** [comment]
@jamesmartin thanks, really appreciate. I'll move forward with this, then we can drop

**Comment by tagliala** [comment]
@jamesmartin all green here, no changes to production code, should be safe to merge and will fix the failing badge

**Review by jamesmartin — APPROVED** [review]

**Comment by jamesmartin** [comment]
Thanks again, @tagliala! ✨

**Pull request merged**
