### PR TITLE
update active_support version to ~> 4.2.0

### PR DESCRIPTION
**Pull request by jmarceli**
All tests were OK

### CODE REVIEW

**Comment by jamesmartin** [comment]
I don't think we want to force people to use a minimum of 4.2.0.

Is it possible to just specify `>= 4.1.9`? Or will that require divergent changes to the active support requires?

**Comment by jmarceli** [comment]
I've updated my pull request and run tests for both activesupport versions (4.1.9 and 4.2.0), everything was fine.

**Comment by jamesmartin** [comment]
Thanks, @jmarceli. I'll take a look today and aim to release an update this evening if everything looks good.

**Comment by jamesmartin** [comment]
Fixed in [v0.5.1](https://github.com/jamesmartin/inline_svg/blob/master/CHANGELOG.md#051---2015-03-30)

**Pull request merged**
