### PR TITLE
Unique IDs for a11y Elements

### PR DESCRIPTION
**Pull request by jamesmartin**
Addresses #38. Generates a simple SHA1 hash of the title and description element's ID attributes to ensure uniqueness when adding the `aria-labelled-by` attribute to the SVG root node.

/cc @tysongach is this what you had in mind?

### CODE REVIEW

**Comment by jamesmartin** [comment]
Actually, thinking about it a bit more. SHA1 is going to be unsuitable for an ID because it can generate garbage like this:

```
irb(main):007:0> OpenSSL::Digest::SHA1.digest("some-value")
=> "\xC1\xB2B\x94\xF0\x0E(\x16\x05\xF9\xDDj)\x86\x12\xE3\x06\x00b\xB4"
```

I don't think we want *that* as an ID. Might have to switch to a random alpha/numeric generator.

**Comment by jamesmartin** [comment]
Worked around the SHA1 byte-garbage problem by hexencoding the bytes, converting to a base16 fixnum and then working back to base36 to get a-zA-Z0-9. Should be fine.

**Comment by tysongach** [comment]
Sounds great! Mind posting an example input/output?

**Comment by jamesmartin** [comment]
> Mind posting an example input/output?

@tysongach here's an example from my [test rails app](https://github.com/jamesmartin/inline_svg_test_app/blob/afe70d7af45807b3439b2b359b6d6ea5e050153a/app/views/welcome/index.html.haml#L20-L22):

```ruby
  %h2 SVG With Accessibility Labels (Aria)
  .svg
    = inline_svg('iconmonstr-glasses-12-icon.svg', class: 'medium-blue', title: 'An SVG', desc: 'This is my SVG. There are many like it. You get the picture', aria: true)
```

---

screen shot 2016-06-29 at 4 09 58 pm

---

What do you think?

**Comment by tysongach** [comment]
@jamesmartin I think this is great!

**Pull request merged**
