### PR TITLE
Add rubocop

### PR DESCRIPTION
**Pull request by meowsus**

### CODE REVIEW

**Comment by meowsus** [comment]
My editor was losing it's mind, so I figured i'd make it shut up. If you want, I can go through and appease lord rubocop, but I just wanted to first see if this is something you'd like to have done.

**Comment by jamesmartin** [comment]
@meowsus thanks for the PR. Seems like a reasonable place to start.

> If you want, I can go through and appease lord rubocop

If you really want to do it all in one hit, feel free. Otherwise I'm happy to gradually appease rubocop as we're working inside the offending files.

**Comment by tysongach** [comment]
Perhaps we could add [Hound](https://houndci.com/), as well, which can reference this RuboCop config and comment on PRs automatically, with any violations. It’s free for open source!

**Comment by meowsus** [comment]
With fingers crossed I ran rubocop with the -a option, but the tests borked.

I think the best course of action is to just commit the TODO and work through the offenses as needed. 

Adding Hound would allow people to be aware of their responsibility to this effort in their PRs as well. It seems like a good idea.

**Comment by jamesmartin** [comment]
> I think the best course of action is to just commit the TODO and work through the offenses as needed.

Sounds good 👍 

Thanks for getting the ball rolling on this, @meowsus!

**Comment by jamesmartin** [comment]
> Perhaps we could add Hound, as well, which can reference this RuboCop config and comment on PRs automatically, with any violations. It’s free for open source!

@tysongach good idea. I'll look into doing that once the current Rubocop TODOs are all completed.

**Pull request merged**
